namespaces:
  - avisa-ia-dev
  - avisa-ia-staging
  - avisa-ia-homolog
  - avisa-ia-prod

# Subconjunto de "namespaces" que ainda nao existem / nao tem VaultAuth
# proprio criado por outro app (avisa-ia-dev/staging/prod ja tem, via
# avisa-ia-vault-setup).
newNamespaces:
  - avisa-ia-homolog
