apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azahar
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: homelab
  sources:
    - repoURL: https://henriqzimer.github.io/azahar-helm-chart
      chart: azahar
      targetRevision: "1.4.5"
      helm:
        valueFiles:
          - $values/values/gaming/azahar.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
