apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rpcs3
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: homelab
  sources:
    - repoURL: https://henriqzimer.github.io/rpcs3-helm-chart
      chart: rpcs3
      targetRevision: "1.0.0"
      helm:
        valueFiles:
          - $values/values/gaming/rpcs3.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
