apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shadps4
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: homelab
  sources:
    - repoURL: https://henriqzimer.github.io/shadps4-helm-chart
      chart: shadps4
      targetRevision: "1.3.2"
      helm:
        valueFiles:
          - $values/values/gaming/shadps4.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gaming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
