apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-secrets-sync
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: minio-credentials
  refreshAfter: 1m
  destination:
    name: minio-root-credentials
    create: true
    overwrite: true
    type: Opaque
    transformation:
      templates:
        rootUser:
          text: '{{ "{{" }} get .Secrets "rootUser" {{ "}}" }}'
        rootPassword:
          text: '{{ "{{" }} get .Secrets "rootPassword" {{ "}}" }}'
