apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provider-proxmox
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: homelab
  sources:
    - repoURL: ghcr.io/sergelogvinov/charts
      chart: karpenter-provider-proxmox
      targetRevision: "0.4.9"
      helm:
        valueFiles:
          - $values/values/scheduling/karpenter-provider-proxmox.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      path: charts/karpenter-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
