apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: homelab
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "1.20.2"
      helm:
        valueFiles:
          - $values/values/networking/cert-manager.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      path: charts/cert-manager-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
