apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: homelab
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "41.3.0"
      helm:
        valueFiles:
          - $values/values/networking/traefik.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
