apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: homelab
  sources:
    - repoURL: https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
      chart: defectdojo
      targetRevision: "1.9.48"
      helm:
        valueFiles:
          - $values/values/security/defectdojo.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
