apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: velero-secrets-sync
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  # Mesmo path do minio-credentials (charts/minio-extras) - reaproveita o
  # mesmo par rootUser/rootPassword, so muda o formato do secret de destino.
  path: minio-credentials
  refreshAfter: 1m
  destination:
    name: velero-minio-credentials
    create: true
    overwrite: true
    type: Opaque
    transformation:
      templates:
        cloud:
          text: |
            [default]
            aws_access_key_id={{ "{{" }} get .Secrets "rootUser" {{ "}}" }}
            aws_secret_access_key={{ "{{" }} get .Secrets "rootPassword" {{ "}}" }}
