apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-credentials-sync
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: vaultwarden-credentials
  refreshAfter: 1m
  destination:
    name: vaultwarden-credentials
    create: true
    overwrite: true
    type: Opaque
    transformation:
      templates:
        username:
          text: '{{ "{{" }} get .Secrets "username" {{ "}}" }}'
        password:
          text: '{{ "{{" }} get .Secrets "password" {{ "}}" }}'
        admin_token:
          text: '{{ "{{" }} get .Secrets "admin_token" {{ "}}" }}'
        smtp_username:
          text: '{{ "{{" }} get .Secrets "smtp_username" {{ "}}" }}'
        smtp_password:
          text: '{{ "{{" }} get .Secrets "smtp_password" {{ "}}" }}'
