apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: streaming-broker-secret-sync
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: k8s-homelab
  path: streaming-broker
  refreshAfter: 1m
  destination:
    name: streaming-broker-secret
    create: true
    overwrite: true
    type: Opaque
    transformation:
      templates:
        STREAMING_BROKER_SECRET:
          text: '{{ "{{" }} get .Secrets "STREAMING_BROKER_SECRET" {{ "}}" }}'
        BROKER_SECRET:
          text: '{{ "{{" }} get .Secrets "BROKER_SECRET" {{ "}}" }}'
