apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: development
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: homelab
  sources:
    - repoURL: https://portainer.github.io/k8s/
      chart: portainer
      targetRevision: "239.2.0"
      helm:
        valueFiles:
          - $values/values/monitoring/portainer.yaml
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/henriqzimer/argocd-k8s-homelab.git
      targetRevision: main
      path: charts/portainer-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
